### ISSUE TITLE
Statistics for positive selection

### ISSUE THREAD

**Issue by jeslipp** [felicityallen/JACKS#15]
Thank you for your great tool. Would it be possible to provide statistics for positive selection, either in addition to negative selection or as an alternative using a command line flag?

This would make JACKS more versatile and would cover the analysis of enrichment screens.

**Comment by lp2** [comment]
Give us a few days to discuss - in theory, the p-values for the other tail
are straightforward to include, but in practice there can be a difference
between theory and practice as usual :)

**Comment by jeslipp** [comment]
Thank you very much for considering my suggestion. Any update on how easy or difficult this would be to implement?

**Comment by lp2** [comment]
Apologies Jesse - we are both separately on parental leave, so
communications are slow. I don't want to commit to additional features as
it's Felicity's repo :)

The reported p-value is a one-sided tail p-value computed from the
posterior of w. To get the probability for the other tail (positive
selection), it is sufficient to use (1-p) in your downstream processing. I
would recommend using both the effect size (w) and the 1-p for this purpose
- first for the raw effect for ranking, the other for its measurability for
filtering.

@Felicity - do you see any problems with this approach?

  Leo

**Comment by jeslipp** [comment]
No worries. Many thanks for your reply and suggestion. If Felicity is fine with it, I would use it as a work-around in the meantime to further promote the use of JACKS in my organization.

**Comment by felicityallen** [comment]
Hi Jesse,

Apologies for my delayed response, my 2 month old doesn't give me a lot of
time/sleep.

Leo is correct about using 1-p, the only issue I can think of with this
would be numerical accuracy for p values below 1e-6 since the p-value
output file only goes to 6 significant figures.

In any case, I've just pushed a change to github to support positive
selection. Add "--positive" to the command line arguments to switch to
positive selection. Hope this helps!

Cheers,
Felicity

**Comment by jeslipp** [comment]
Hi Felicity, 

Great, thank you very much for providing this option! 

Best, 
Jesse
